### ISSUE TITLE
Updated vCD Provider Breaks Edge Gateway External Networks Data Sources

### ISSUE THREAD

**Issue by shallcrm** [IBM-Cloud/vmware-solutions-shared#1]
FYI ... Since this tutorial was originally published the Terraform provider for vCloud Director has been updated, deprecating the "external_networks" and "default_external_gateway" attributes for the "vcd_edgegateway" resource.  These changes break several of the data sources you use to set outputs.

I was able to circumvent this be explicitly requiring the older version 2.9.0 of the vcd provider in "versions.tf".   (Unfortunately I was not able to successfully figure out how to update the code to be compatible with the new version 3.0.0 of the provider.)

 **versions.tf**:
terraform {
  required_version = ">= 0.12"
  required_providers {
    vcd = {
      version  = "=2.9.0"
    }
  }
}

**Comment by dprosper** [comment]
thank you for letting us know, I will look into it.

**Comment by dprosper** [comment]
for now we can't upgrade to version 3.0 of the vCD provider, we are going to lock to [version 2.9](https://github.com/IBM-Cloud/vmware-solutions-shared/commit/cfe1a9fd9a05779d088814814524b20a0733b48c) until VMWare provides a solution:

https://github.com/vmware/terraform-provider-vcd/issues/588
https://github.com/vmware/terraform-provider-vcd/issues/577

**Comment by dprosper** [comment]
@shallcrm VMWare provided a pre-release update to the provider which I tested and it works, but we will have to wait for it to be released later this year (fingers crossed) before we update the template and tutorial to reflect the use of v3.x, for now the template will remain on v2.9.0 and should work.  

Thank you for reporting. We will track the update to 3.x in an internal system.
