### ISSUE TITLE
terraform init fails

### ISSUE THREAD

**Issue by karthick-kk** [IBM-Cloud/vmware-solutions-shared#2]
Terraform unable to pull the required vcd plugin from registry.

` 
/tmp/vmware-solutions-shared  master  terraform init                                                                                                                                                               
Initializing modules...
- ibm_vmware_solutions_shared_instance in modules/ibm-vmware-solutions-shared-instance

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/vcd versions matching "2.9.0"...

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/vcd:
no available releases match the given constraints 2.9.0

 /tmp/vmware-solutions-shared  master
`

**Comment by l2fprod** [comment]
- fixed with the latest code
- requires Terraform 0.13
